Algoritmo "ATIVIDADE 06 - AVALIAÇÃO"

Var
 nomes:vetor[1..10] de caractere
 contador:inteiro
 nomeExtra:caractere


Inicio
para contador de 1 ate 10 faca
  escreval("Digite 10 nomes:")
  leia(nomes[contador])
fimPara
limpatela()
  escreval("Digite mais um nome:")
    leia(nomeExtra)
se(nomeExtra<>nomes[contador])entao
   escreval("Não achei!!")
senao
 se(nomeExtra = nome[contador])entao
 escreval("Acheiiii!!")
fimse
fimse
Fimalgoritmo